[install_deps]
run("apt-get install cmake git")

[init]
run("git submodule update --init --recursive")

[build]
if not exists("./build"):
    makedirs("./build")
with cd("./build"):
    run("cmake ..")
    run("make -j 2")

[run_unit-tests]
# try:
with cd("./build/tests/"):
    run("./unit-tests/tests")
# except Exception:
    # print "Seems dir ./build/tests/ can't be reached ..."

[a]
if True:
    a=232
    print a